# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/198AFLuXzokoK2xI8eCiitmizOjSwuHv5
"""

import pandas as pd
from fincaprueba import fincaraiz
from metrocuadrado import metrocuadrado
from realityserver import realityserver
from lonja import lonja
from bs4 import BeautifulSoup

def scrap_total():

    data_historica = pd.read_csv("data_contatenada.csv", sep=',')

    # EXTRAER DATA WEB SCRAPP
    try:
        df1 = fincaraiz()
    except Exception as e:
        print(f"Error en fincaraiz(): {e}")
        df1 = pd.DataFrame()  # Crear un DataFrame vacío en caso de error

    try:
        df2 = metrocuadrado()
    except Exception as e:
        print(f"Error en metrocuadrado(): {e}")
        df2 = pd.DataFrame()

    try:
        df3 = realityserver()
    except Exception as e:
        print(f"Error en realityserver(): {e}")
        df3 = pd.DataFrame()

    try:
        df4 = lonja()
    except Exception as e:
        print(f"Error en lonja(): {e}")
        df4 = pd.DataFrame()

    # CONCATENAR DATA
    data_total = pd.concat([data_historica, df1, df2, df3, df4])
    data_total.drop_duplicates(['idpropiedad'], inplace=True)
    data_total.reset_index(drop=True, inplace=True)

    data_total["tipopropiedad"] = data_total["tipopropiedad"].str.strip()

    data_total.to_csv("data_contatenada.csv", index=False)

    return data_total


